env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - standard-with-typescript
  - plugin:vue/vue3-recommended
  - prettier
parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: latest
  sourceType: module
  project: ["./tsconfig.json", "./tsconfig.node.json"]
  extraFileExtensions: [".vue"]
plugins:
  - vue
rules: {}
